# Changes here will be overwritten by Copier
_commit: 1.1.3
_src_path: https://github.com/pawamoy/copier-pdm.git
author_email: amvillalobos@uc.cl
author_fullname: Adolfo Villalobos
author_username: AdolfoVillalobos
copyright_date: '2023'
copyright_holder: Adolfo Villalobos
copyright_holder_email: amvillalobos@uc.cl
copyright_license: MIT License
insiders: false
project_description: An example airflow project using modern python tools
project_name: example-airflow-project
python_package_command_line_name: example-airflow-project
python_package_distribution_name: example-airflow-project
python_package_import_name: example_airflow_project
repository_name: example-airflow-project
repository_namespace: AdolfoVillalobos
repository_provider: github.com
